# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'VodaFoodies' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  ###### Pods for VodaFoodies ######
  # Firebase Dependecies
  pod 'Firebase/Core'
  pod 'Firebase/Auth'

  #Facebook Dependecies
  pod 'FacebookCore'
  pod 'FacebookLogin'

  #Kingfisher for loading and caching images
  pod 'Kingfisher', '~> 3.0'


  target 'VodaFoodiesTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
